# -*- coding: utf-8 -*-
"""Text_Generator_Kalyani_Shinde.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Xrr_L33UGOhta8HvJiBYhSihhhCQPXUY
"""

!pip install transformers gradio torch

from transformers import pipeline

# Load GPT-2 pre-trained model
generator = pipeline("text-generation", model="gpt2")

# Try a sample input
prompt = "Artificial intelligence will change the future by"
output = generator(prompt, max_length=100, num_return_sequences=1)

print("Generated Text:\n", output[0]['generated_text'])

import gradio as gr

def generate_text(prompt, max_len, temp):
    result = generator(prompt, max_length=max_len, temperature=temp)[0]['generated_text']
    return result

# Create Gradio Interface
demo = gr.Interface(
    fn=generate_text,
    inputs=[
        gr.Textbox(lines=2, label="Enter your prompt"),
        gr.Slider(20, 300, value=100, label="Max Length"),
        gr.Slider(0.1, 1.0, value=0.7, label="Temperature")
    ],
    outputs="text",
    title="GPT-2 Text Generator"
)

demo.launch()